@@include('jQuery.js');
@@include('swiper-bundle.js');
@@include('jquery.nicescroll.min.js');
@@include('slick.min.js'); 
@@include('smoothScroll/jquery-ui-1.8.23.custom.min.js'); 
@@include('smoothScroll/jquery-ui-1.10.3.custom.min.js'); 
@@include('smoothScroll/jquery.kinetic.min.js'); 
@@include('smoothScroll/jquery.mousewheel.min.js'); 
@@include('smoothScroll/jquery.smoothdivscroll-1.3-min.js'); 